### ISSUE TITLE
execl return errno 2 when running mono mode

### ISSUE THREAD

**Issue by na3na3na** [domschrei/mallob#17]
I am trying to run a mono job using mallob using the following command:

./mallob -mono-app=sat -mono=/some/path/myproblem.cnf

but i keep getting this execl return errno 2 error which seems to imply that mallob is unable to find my cnf file?

Any idea where i could start debugging this

**Comment by anon943310** [comment]
This error indicates that mallob can't find the SAT solving subprocess executable. You need it at `build/mallob_sat_process` if you use the default build options. You can also specify a different path with `-DMALLOB_SUBPROC_DISPATCH_PATH`, see the README.

**Comment by domschrei** [comment]
This error indicates that mallob can't find the SAT solving subprocess executable. You need it at `build/mallob_sat_process` if you use the default build options. You can also specify a different path with `-DMALLOB_SUBPROC_DISPATCH_PATH`, see the README.
