### ISSUE TITLE
[Test suite] unrecognized argument oversubscribe

### ISSUE THREAD

**Issue by marino-mrc** [domschrei/mallob#7]
Hi,
when running the test suite, I get the following error:
./scripts/run/systest.sh mono
--------------------------------------------------------------------------------
[1] -np 1 -t=1 -mono=instances/r3sat_300.cnf -satsolver=llck -appmode=fork -assertresult=SAT
[mpiexec@challenger] match_arg (utils/args/args.c:163): unrecognized argument oversubscribe
[mpiexec@challenger] HYDU_parse_array (utils/args/args.c:178): argument matching returned error
[mpiexec@challenger] parse_args (ui/mpich/utils.c:1642): error parsing input array
[mpiexec@challenger] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1694): unable to parse user arguments
[mpiexec@challenger] main (ui/mpich/mpiexec.c:148): error parsing parameters

I think the problem is related to the fact that the "oversubscribe" option is unsupported in my version of mpirun (3.3.2)
It can be easily fixed by removing the "--oversubscribe" option in the "run()" function in scripts/run/systest_commons.sh but I don't know if you require a specific version of mpi for some reason.

Thank you.
Regards,
Marco

**Comment by domschrei** [comment]
Hi Marco, thanks for the issue. In fact I tested Mallob on OpenMPI and Intel MPI, but never on MPICH. The tests are written with OpenMPI in mind – I should be more explicit with that in the README. Do the tests succeed for you (with MPICH) without the oversubscribe option?

**Comment by marino-mrc** [comment]
Yes, Tests work without any issue if I remove the "oversubscribe" option in the function mentioned in my previous comment. Also, note that mpich supports "oversubscribe" in version 3.0 (as mentioned here: https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php)

OT: I have many technical questions because I'm thinking to use Mallob in another project. Is there a better place where I can ask or can I open multiple issues on Github? Thanks!

Regards,
Marco

**Comment by domschrei** [comment]
That's cool. I might do some testing with MPICH myself and then "officially" support MPICH as well. But for now I think I'll update the documentation that the test script expects OpenMPI.

(The link you provided points to OpenMPI, not MPICH, right? Or am I missing something?)

If you have several further questions regarding Mallob, maybe we can just sort them out via email? dominik.schreiber ~at~ kit.edu

**Comment by marino-mrc** [comment]
Ops, I'm sorry! my fault! Doing this while I'm working on many other things :) 

About my questions about the project: Sure! It will be great. Please, give me the time to prepare my questions, I'm doing several tests in my home lab actually. Thanks!

**Comment by marino-mrc** [comment]
Just tested with Openmpi (sudo apt install openmpi-bin) and it works on Ubuntu 20.04 LTS with the "oversubscribe" flag.

Thanks.
Regards,
Marco
